### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by blkhwks19** [gadhagod/Hyrule-Compendium-API#16]
I know the images are in development so you may or may not be aware of these, but just wanted to point them out in case you weren't.

I came across 3 missing images:
https://botw-compendium.herokuapp.com/api/v2/entry/golden_bow/image
https://botw-compendium.herokuapp.com/api/v2/entry/golden_claymore/image
https://botw-compendium.herokuapp.com/api/v2/entry/luminous_ore_deposit/image

I also came across 1 broken image. The image is actually there and works just fine but the url in the entry has a typo:
https://botw-compendium.herokuapp.com/api/v2/entry/rare_or_deposit/image  ('ore' is misspelled and is missing the 'e')

**Comment by gadhagod** [comment]
Thanks for reporting this @blkhwks19! I see that a few of the images are broken or misspelled because of the website I scraped them from. I'll have those fixed soon.

Again, greatly appreciated!

**Comment by gadhagod** [comment]
Fixed in https://github.com/gadhagod/Hyrule-Compendium-API/commit/0821093fe9604eb7be1f0f38b478d36264238c15. :)
