### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by VagrantApe** [gadhagod/Hyrule-Compendium-API#24]
The API is currently throwing a 500 at https://botw-compendium.herokuapp.com/api/v2 endpoint

**Comment by gadhagod** [comment]
This error seems to have been caused by downtime on the database I'm dependent on. This problem started less than six hours ago according the [API tests](https://github.com/gadhagod/Hyrule-Compendium-API/actions). I'm working on a temporary fix right now.

Thanks for pointing this out @VagrantApe!

**Comment by gadhagod** [comment]
FYI Rockset's uptime monitor is [here](https://status.rockset.com/?utm_source=embed).

**Comment by VagrantApe** [comment]
Thanks for the quick response.

**Comment by gadhagod** [comment]
@VagrantApe [all systems back up](https://github.com/gadhagod/Hyrule-Compendium-API/runs/3335673124?check_suite_focus=true) :)
