### ISSUE TITLE
Servers down

### ISSUE THREAD

**Issue by jmrtno** [gadhagod/Hyrule-Compendium-API#44]
Hi! The API is really impressive, great work! Just to inform you, the servers have been down for a few hours. When this happens, are downtime posted somewhere where developers using the API can check the status of the servers? Thanks in advance
![Captura2](https://github.com/user-attachments/assets/9df446d1-02ad-41b3-8e58-76b34d9f62f4)

**Comment by gadhagod** [comment]
Hello @jmrtno,

Thanks for reporting this. `v3` endpoints are functional again as of a few minutes ago. I'm working on a fix to get `v2` endpoints up and running again.

There is no uptime page as of now. The closest thing we have at the moment is the [GitHub actions log](https://github.com/gadhagod/Hyrule-Compendium-API/actions/workflows/deployed-api-tests.yml). For this reason, I'll be using this thread to post updates.

**Comment by jmrtno** [comment]
> Hello @jmrtno,
> 
> Thanks for reporting this. `v3` endpoints are functional again as of a few minutes ago. I'm working on a fix to get `v2` endpoints up and running again.
> 
> There is no uptime page as of now. The closest thing we have at the moment is the [GitHub actions log](https://github.com/gadhagod/Hyrule-Compendium-API/actions/workflows/deployed-api-tests.yml). For this reason, I'll be using this thread to post updates.

Thank you so much!

**Comment by gadhagod** [comment]
Everything's back up! [Tests are now passing](https://github.com/gadhagod/Hyrule-Compendium-API/actions/runs/9921393790). I really apologize for the inconvenience. Please let me know if you come across any issues.
