### ISSUE TITLE
The creatures category returns non-creature content

### ISSUE THREAD

**Issue by kawazoe** [gadhagod/Hyrule-Compendium-API#7]
I was looking around the dataset and I noticed that there is a lot of "non-creature" content returned by the creatures endpoint. For instance, you get stuff like "golden claymore" with id 262 in the non-food sub-category. I'm a bit confused about what your concept of a "creature" is within the domain of this API.

It also doesn't match the data in the creatures json file which only have 83 entries. Is this a bug?

**Comment by gadhagod** [comment]
Oh no! It seems I accidentally added the weapons to the creatures category. Working on a fix. Thanks!

**Comment by kawazoe** [comment]
I think I saw "luminous ore" in there as well, so there might be more than just weapons.

**Comment by gadhagod** [comment]
Fixed up now! I just deleted the collection and remade it, so it should only have creatures. There are only 83 entries now. 
I'll check to make sure that this didn't happen to any other categories.
Thanks a lot!
